apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ${CLUSTER_NAME}
  # region: eu-north-1
  region: us-east-1
  version: "${CLUSTER_VERSION}"
  tags:
    environment: "${CLUSTER_NAME}"

managedNodeGroups:
  - name: ${CLUSTER_NAME}-ng-1
    instanceType: t3.medium
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 10
    tags:
      environment: "${CLUSTER_NAME}"
    propagateASGTags: true
    iam:
      withAddonPolicies:
        certManager: true

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "MohamedMSaeed"
      repository: "wg-test"
      private: "true"
      branch: "main"
      namespace: "flux-system"
      path: "clusters/${CLUSTER_NAME}/management"
