apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hamada
  region: us-east-1
  version: 1.21
  tags:
    environment: hamada

managedNodeGroups:
  - name: hamada-ng-1
    instanceType: t3.medium
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    volumeSize: 10
    tags:
      environment: hamada
    propagateASGTags: true
    iam:
      withAddonPolicies:
        certManager: true

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "MohamedMSaeed"
      repository: "wg-test"
      private: "true"
      branch: "main"
      namespace: "flux-system"
      path: "clusters/hamada"
