name: elastalert

on:
  push:
    paths:
      - 'clusters/*/eksctl-cluster.yaml'

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      # - name: setup aws credentials
      #   if: ${{ inputs.management-cluster-kind == 'eks' }}
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.WGE_EKS_AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.WGE_EKS_AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      # - name: Install eksctl
      #   if: ${{ inputs.management-cluster-kind == 'eks' }}
      #   run: |
      #     curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      #     sudo mv /tmp/eksctl /usr/local/bin
      #     eksctl version
      #     eksctl get clusters
      # - name: Install aws-cli
      #   if: ${{ inputs.management-cluster-kind == 'eks' }}
      #   run: |
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install --update
      #     aws --version
      # - name: Install aws-iam-authenticator
      #   if: ${{ inputs.management-cluster-kind == 'eks' }}
      #   run: |
      #     wget https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v0.5.7/aws-iam-authenticator_0.5.7_${{ inputs.os-name }}_amd64 -O /tmp/aws-iam-authenticator
      #     chmod +x /tmp/aws-iam-authenticator
      #     sudo mv /tmp/aws-iam-authenticator /usr/local/bin
      #     aws-iam-authenticator version
      # - name: Provision the cluster
      #   run: |
      #     echo "cluster name"
      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v29.0.3
        with:
          dir_names: "true"

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files-dir-names.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

  # install-WGE:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "connect-to-cluster"
  #       run: |
  #         echo "connect-to-cluster"
  #     - name: Install clusterctl
  #       run: |
  #         curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.4/clusterctl-${{ inputs.os-name }}-amd64 -o clusterctl
  #         chmod +x ./clusterctl
  #         sudo mv ./clusterctl /usr/local/bin/clusterctl
  #         clusterctl version

  #     - name: "install WGE"
  #       run: |
  #         echo "install all"
